# Generated by Django 6.0.6 on 2026-06-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_brand', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=100, verbose_name='Modelo')),
                ('vehicle_year', models.CharField(blank=True, default='', max_length=10, verbose_name='Ano')),
                ('vehicle_engine', models.CharField(blank=True, default='', max_length=50, verbose_name='Motorizacao')),
                ('vehicle_fuel', models.CharField(blank=True, default='', max_length=30, verbose_name='Combustivel')),
                ('vehicle_transmission', models.CharField(blank=True, default='', max_length=30, verbose_name='Transmissao')),
                ('vehicle_mileage', models.IntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('vehicle_plate', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa')),
                ('codes', models.JSONField(default=list, verbose_name='Codigos OBD-II')),
                ('overall_severity', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Critica')], default='Baixa', max_length=10, verbose_name='Criticidade Geral')),
                ('total_codes', models.IntegerField(default=0, verbose_name='Total de Codigos')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Resumo')),
                ('conclusion', models.TextField(blank=True, default='', verbose_name='Conclusao')),
                ('results', models.JSONField(default=list, verbose_name='Resultados')),
                ('report_html', models.TextField(blank=True, default='', verbose_name='HTML do Relatorio')),
            ],
            options={
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oficina Mecanica Premium', max_length=200, verbose_name='Nome da Oficina')),
                ('address', models.CharField(default='Rua Principal, 123 - Centro', max_length=300, verbose_name='Endereco')),
                ('phone', models.CharField(default='(11) 3456-7890', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('mechanic_name', models.CharField(default='Mecanico Responsavel', max_length=200, verbose_name='Mecanico Responsavel')),
                ('mechanic_credential', models.CharField(default='CTPS / CFC XXXXX', max_length=100, verbose_name='Credencial')),
            ],
            options={
                'verbose_name': 'Configuracao da Oficina',
                'verbose_name_plural': 'Configuracoes da Oficina',
            },
        ),
    ]
