# Generated by Django 6.0.6 on 2026-06-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsettings',
            name='address',
            field=models.CharField(default='Rua Santa Helena, 12 - Bairro da Paz', max_length=300, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='name',
            field=models.CharField(default='Oficina Original', max_length=200, verbose_name='Nome da Oficina'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='phone',
            field=models.CharField(default='(92) 99389-8610', max_length=20, verbose_name='Telefone'),
        ),
    ]
