# Generated by Django 6.0.6 on 2026-06-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_shopsettings_address_alter_shopsettings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='client_document',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do Cliente'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone do Cliente'),
        ),
    ]
